server:
  port: 8001

mybatis:
  type-aliases-package: org.watermelon.api.entity
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  mapUnderscoreToCamelCase: true

spring:
  application:
    name: distribute-provider-dept
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dis_demo?serverTimezone=UTC
    username: root
    password: 105036
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    instance:
      instance-id: distribute-provider-dept
