server:
  port: 8003

mybatis:
  type-aliases-package: org.watermelon.api.entity
  mapper-locations: classpath:mapper/*.xml
  mapUnderscoreToCamelCase: true

spring:
  application:
    name: distribute-provider-dept
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dis_demo_03?serverTimezone=UTC
    username: root
    password: 105036
    type: com.alibaba.druid.pool.DruidDataSource

#设置向Eureka进行服务注册
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka/
      #构建Eureka集群时，向多个Eureka实例注册服务
      #当多个Eureka的hostname相同时，微服务默认向defaultZone的最后一个实例进行注册
      defaultZone: http://localhost02:7002/eureka/,http://localhost01:7001/eureka/
    #修改微服务名称application-id
    instance:
      instance-id: distribute-provider-dept-03
