spring:
  profiles: dev
  active: dev

---
server:
  port: 9202

spring:
  profiles: dev
  application:
    name: distribute-config-dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost02:7002/eureka/,http://localhost01:7001/eureka/

---
server:
  port: 9203

spring:
  profiles: test
  application:
    name: distribute-config-dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost02:7002/eureka/,http://localhost01:7001/eureka/